name: gold-price-prediction
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pandas
  - numpy=1.23.5
  - matplotlib
  - scikit-learn
  - statsmodels
  - xgboost
  - lightgbm
  - yfinance
  - requests
  - beautifulsoup4
  - nltk
  - spacy
  - textblob
  - jupyterlab
  - seaborn
  - pip
  - tensorflow==2.13