name: gold-price-prediction
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pandas
  - numpy=1.23.5
  - matplotlib
  - scikit-learn
  - xgboost
  - yfinance
  - requests
  - jupyterlab
  - seaborn
  - tensorflow==2.13
  - backtesting
  - json
  - requests
